[package]
name = "ascendant"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arrayvec = "0.7.6"
chromiumoxide = "0.8.0"
futures = "0.3.31"
itertools = "0.14.0"
seq-macro = "0.3.6"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
